### ISSUE TITLE
NullPointerException when specifying a non-existing keyspace or table in either clusters (master or replica)

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-cdc-java#17]
The title says it all. For example, run:
```
java -cp replicator.jar com.scylladb.cdc.replicator.Main -k ks1 -t table1 -s 127.0.0.10 -d 127.0.0.20 -cl one -m delta
```
without previously creating `ks1` or `table1`. Result:
```
Master thread failed: null                                                                                                                                    
java.lang.NullPointerException                                                                                                                                
        at com.scylladb.cdc.replicator.ReplicatorConsumer.<init>(ReplicatorConsumer.java:41)
        at com.scylladb.cdc.replicator.Main.lambda$startReplicator$0(Main.java:55)                                                                            
        at com.scylladb.cdc.lib.LocalTransport.configureWorkers(LocalTransport.java:79)       
        at com.scylladb.cdc.model.master.Master.run(Master.java:88)                                                                                           
        at com.scylladb.cdc.lib.MasterThread.run(MasterThread.java:32)                                                                                        
```

**Comment by haaawk** [comment]
What would be the expected behaviour? Stopping gracefully?

**Comment by kbr-** [comment]
Yes

**Comment by avelanarius** [comment]
Pushed a commit that fixes this exact issue. However, still no other validation is done. (for example whether the destination cluster has a correct schema).
